### PR TITLE
Configure mobx 

### PR DESCRIPTION
**Pull request by sergous**
https://github.com/dtpstat/website/issues/3

### CODE REVIEW

**Comment by sergous** [comment]
We need state management for save components slim, including props and move all business logic out of them. Please review this aproach of connecting mobx and give me your feedback.

**Comment by kachkaev** [comment]
Hmm I’m not sure we can benefit much from mobx, at least at this stage of the project. Built-in hooks is what React team recommends for modern React. Unlike for centralized stores, this approach simplifies onboarding, is compatible with SSR and concurrency and also scales well to thousands of components. Happy to discuss mobx in a call, maybe I’m just out of date on it 🙂

**Comment by sergous** [comment]
Hm,  I like hooks, but luck of experience. Need to explore how to have
shared store between components, may be create custom hook for that purpose.

пн, 13 дек. 2021 г., 07:40 Alexander Kachkaev ***@***.***>:

**Comment by sergous** [comment]
Replaced with hooks.

**Pull request closed without merging**
